defaults:
  - default

model:
  _target_: src.models.vggnet_fcn_segmentation_model.VGGNetFCNSegmentationModel
  segmentation_criterion: null
  classification_criterion: null
  seg_num_classes: 1
  cls_num_classes: 3
  seg_weight: 0.99
  cls_weight: 0.01
  vggnet_type: vgg11_bn
  fcn_type: fcn8
