# configs/datamodule/breast_cancer_datamodule.yaml
_target_: src.datamodules.breast_cancer_dataloader_module.BreastCancerDataLoaderModule

# Include data config to ensure it's available
# This is the key change
defaults:
  - /data: default
  - _self_

  # This allows injecting any dataset configuration
transforms:
  train_transforms:
    - _target_: torchvision.transforms.v2.Resize
      size: [256, 256]
      antialias: True

    # Augmentations
    - _target_: torchvision.transforms.v2.RandomHorizontalFlip
    - _target_: torchvision.transforms.v2.RandomVerticalFlip
    - _target_: torchvision.transforms.v2.ElasticTransform
      alpha: 50.0
      sigma: 5.0

  val_transforms:
    - _target_: torchvision.transforms.v2.Resize
      size: [256, 256]

  test_transforms:
    - _target_: torchvision.transforms.v2.Resize
      size: [256, 256]
