# configs/datamodule/breast_cancer_datamodule.yaml
_target_: src.datamodules.breast_cancer_dataloader_module.BreastCancerDataLoaderModule

# Include data config to ensure it's available
# This is the key change
defaults:
  - default # load values/arguments from default file
  - /data: default # load values/arguments from data directory (defaults.yaml)
  - _self_ # override with values/arguments from this file
